const API_ROUTES = {
  auth: {
    sign_in: "/auth/login",
    sign_up: "/auth/register",
    social_login: "/auth/social-login",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    profile: "/auth/profile?withPopulate=true",
    send_phone_verification: "/auth/send-phone-verification",
    verify_phone_code: "/auth/verify-phone-code",
    send_email_verification: "/auth/resend-verification",
    verify_email_code: "/auth/verify-email",
    forgot_password: "/auth/forgot-password",
    verify_reset_code: "/auth/verify-reset-code",
    reset_password: "/auth/reset-password",
  },
  file: {
    post: "/save",
    delete: "/delete-file",
    upload: "/files/upload",
  },
  document: {
    list: "/documents?page=:page&pageSize=:pageSize",
    listFilter: "/documents/filters",
    post: "/documents",
    get: "/documents/:id",
    update: "/documents/:id",
    delete: "/documents/:id",
  },
  user: {
    me: "/users/me",
    profile: "/users/me/profile",
    createPhoneNumber: "/users/me/create-phone-number",
    phoneNumber: "/users/me/phone-number",
    resume: "/users/me/resume",
    reauthenticate: "/users/me/reauthenticate",
    changePassword: "/users/me/change-password",
  },
  notificationSettings: {
    me: "/notification-settings/me",
  },
  skills: {
    all: "/skills/all",
    create: "/skills",
  },
  jobs: {
    suggested: "/jobs/suggested",
    save: "/jobs/:id/save",
    unsave: "/jobs/:id/save",
    apply: "/jobs/:id/apply",
    savedIds: "/jobs/savedIds",
    saved: "/jobs/saved",
    applied: "/jobs/applied",
    appliedIds: "/jobs/appliedIds",
    detail: "/jobs/:id",
  },
  companies: {
    followedIds: "/companies/followedIds",
    follow: "/companies/:id/follow",
    detail: "/companies/:id",
    jobs: "/companies/:id/jobs",
  },
};

export default API_ROUTES;
